eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon

springboot-h2:
  ribbon:
    NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RoundRobinRule