eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
#service-hi:
#  ribbon:
#    NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-hi
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign
